require 'capybara'
require 'capybara/rspec'
require 'site_prism'

require 'solidus_page_objects/site_prism/element_checker'

# require components
require 'solidus_page_objects/components/main_navigation'
require 'solidus_page_objects/components/search'
require 'solidus_page_objects/components/header'
require 'solidus_page_objects/components/product_preview'
require 'solidus_page_objects/components/product_list'
require 'solidus_page_objects/components/product_images'
require 'solidus_page_objects/components/property'
require 'solidus_page_objects/components/product'
require 'solidus_page_objects/components/taxon_list'
require 'solidus_page_objects/components/taxonomies'
require 'solidus_page_objects/components/sidebar'
require 'solidus_page_objects/components/cart_item'
require 'solidus_page_objects/components/cart'

# require sections
require 'solidus_page_objects/sections/main_navigation'
require 'solidus_page_objects/sections/search'
require 'solidus_page_objects/sections/header'
require 'solidus_page_objects/sections/product_preview'
require 'solidus_page_objects/sections/product_list'
require 'solidus_page_objects/sections/product_images'
require 'solidus_page_objects/sections/property'
require 'solidus_page_objects/sections/product'
require 'solidus_page_objects/sections/taxon_list'
require 'solidus_page_objects/sections/taxonomies'
require 'solidus_page_objects/sections/sidebar'
require 'solidus_page_objects/sections/cart_item'
require 'solidus_page_objects/sections/cart'

# require pages
require 'solidus_page_objects/pages/home'
require 'solidus_page_objects/pages/products'
require 'solidus_page_objects/pages/cart'
require 'solidus_page_objects/pages/product'
