require 'capybara'
require 'capybara/rspec'
require 'site_prism'

require 'solidus_page_objects/site_prism/element_checker'

# require components
require 'solidus_page_objects/components/checkout'
require 'solidus_page_objects/components/main_navigation'
require 'solidus_page_objects/components/search'
require 'solidus_page_objects/components/header'
require 'solidus_page_objects/components/product/preview'
require 'solidus_page_objects/components/product/list'
require 'solidus_page_objects/components/product/images'
require 'solidus_page_objects/components/product/property'
require 'solidus_page_objects/components/product/similar_item'
require 'solidus_page_objects/components/product/info'
require 'solidus_page_objects/components/product/cart'
require 'solidus_page_objects/components/taxon_list'
require 'solidus_page_objects/components/taxonomies'
require 'solidus_page_objects/components/sidebar'
require 'solidus_page_objects/components/cart_item'
require 'solidus_page_objects/components/cart'
require 'solidus_page_objects/components/order/detail'
require 'solidus_page_objects/components/order/details'
require 'solidus_page_objects/components/order/line_item'
require 'solidus_page_objects/components/order/line_items'
require 'solidus_page_objects/components/order/control'
require 'solidus_page_objects/components/checkout/address'
require 'solidus_page_objects/components/checkout/confirm'
require 'solidus_page_objects/components/checkout/summary'
require 'solidus_page_objects/components/checkout/control'
require 'solidus_page_objects/components/checkout/stock_item'
require 'solidus_page_objects/components/checkout/shipping_method'
require 'solidus_page_objects/components/checkout/delivery'

# require sections
require 'solidus_page_objects/sections/main_navigation'
require 'solidus_page_objects/sections/search'
require 'solidus_page_objects/sections/header'
require 'solidus_page_objects/sections/product/preview'
require 'solidus_page_objects/sections/product/list'
require 'solidus_page_objects/sections/product/images'
require 'solidus_page_objects/sections/product/property'
require 'solidus_page_objects/sections/product/similar_item'
require 'solidus_page_objects/sections/product/info'
require 'solidus_page_objects/sections/product/cart'
require 'solidus_page_objects/sections/taxon_list'
require 'solidus_page_objects/sections/taxonomies'
require 'solidus_page_objects/sections/sidebar'
require 'solidus_page_objects/sections/cart_item'
require 'solidus_page_objects/sections/cart'
require 'solidus_page_objects/sections/order/detail'
require 'solidus_page_objects/sections/order/details'
require 'solidus_page_objects/sections/order/line_item'
require 'solidus_page_objects/sections/order/line_items'
require 'solidus_page_objects/sections/order/control'
require 'solidus_page_objects/sections/checkout/address'
require 'solidus_page_objects/sections/checkout/confirm'
require 'solidus_page_objects/sections/checkout/customer_information'
require 'solidus_page_objects/sections/checkout/summary'
require 'solidus_page_objects/sections/checkout/control'
require 'solidus_page_objects/sections/checkout/stock_item'
require 'solidus_page_objects/sections/checkout/shipping_method'
require 'solidus_page_objects/sections/checkout/delivery'

# require pages
require 'solidus_page_objects/pages/checkout/address'
require 'solidus_page_objects/pages/checkout/confirm'
require 'solidus_page_objects/pages/order'
require 'solidus_page_objects/pages/home'
require 'solidus_page_objects/pages/products'
require 'solidus_page_objects/pages/cart'
require 'solidus_page_objects/pages/product'
require 'solidus_page_objects/pages/checkout/delivery'
